### PR TITLE
added chart 4 and linked it with buttons

### PR DESCRIPTION
**Pull request by prodionov**
added the chart4 and linked it with the filter buttons

Reference #33

### CODE REVIEW

**Review by ghassanmas — COMMENTED** [review]
You you are not pushing the latest changes which includes the other chart

**Review by hasansaad1 — CHANGES_REQUESTED** [review]
update ur branch with the latest changes

**Review by hasansaad1 — APPROVED** [review]

**Review by hasansaad1 — COMMENTED** [review]
puh the fixed one

**Comment by hasansaad1** [comment]
the SVG should be in the div

**Review by hasansaad1 — APPROVED** [review]
ready to merge
@ghassanmas

**Review by ghassanmas — APPROVED** [review]

**Pull request merged**
