### PR TITLE
A copy of the last branch for merging

### PR DESCRIPTION
**Pull request by hasansaad1**
the first chart #8 , with css and routing to the smoking page.
P.S-moved the last branch to a new branch so it can be merged with the master.

### CODE REVIEW

**Review by ghassanmas — APPROVED** [review]

**Review by prodionov — APPROVED** [review]

**Comment by Karyum** [comment]
im taking this PR on since @matthewdking is currently busy with other things

**Review by Karyum — CHANGES_REQUESTED** [review]
before i review code, the styling is weird in the `/smoking` page ( the buttons at the bottom ), and you also have counter next to every chart why 
????

also in the `output` in webpack remove `'public'` so webpack dev server could work without `npm run webpack` and you also have errors in the console

**Comment by prodionov** [comment]
Hi, the word counter will be replaced with the actual counter, that shows you the exact number of smokers in %. We are waiting for this PR to add it.

**Comment by Karyum** [comment]
every chart is a different page correct ? so by now there should have been 5 PR for each chart the reason that there is none here right fuck knows why.

**Review by Karyum — APPROVED** [review]

**Comment by prodionov** [comment]
Charts with small introductions are on one page (as it was designed) and shown to the client in Figma. Other charts were not ready up until now. There is no need to swear in here.

**Comment by Karyum** [comment]
@hasansaad1 @prodionov @ghassanmas im approving this cause i feel like you will not be able to finish this project with a qa. so whats going to happen is no one is going to qa you, do as you please, again we are going to do this, cause i know ( not underestimating here ) you can't finish this project with a qa. 
when i get 3 thumbs up on this comment ( to check you guys have read this ) ill merge this and then you on your own.

**Pull request merged**
